import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "../styles/member.css";
import "../styles/header.css";
import "../styles/filter.css";
import Header from "@/components/Header";
import FilterPanel from "@/components/FilterPanel";


const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};


export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <Header />
                <div className=" panel ">
                    <div className="filter__panel mt-20">
                        <div className="bg-white">
                            <FilterPanel />
                        </div>
                    </div>
                    {children}
                </div>

            </body>
        </html>
    );
}
